name: ai_sdk_google
description: Google Generative AI provider for the AI SDK Dart port.
version: 1.0.0+1
homepage: https://github.com/codenameakshay/ai_sdk_dart
repository: https://github.com/codenameakshay/ai_sdk_dart
resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  ai_sdk_provider: ^1.0.0
  dio: ^5.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.0
