name: ai_sdk_basic_example
description: Basic usage example for AI SDK Dart.
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.11.1

dependencies:
  ai_sdk_dart: ^1.0.0
  ai_sdk_mcp: ^1.1.0
  ai_sdk_openai: ^1.0.0
